let web3;
let contract;
let userAccount;

// Paste your deployed contract address here after running: truffle migrate
const CONTRACT_ADDRESS = "0xCfEB869F69431e42cdB54A4F4f105C19C080A601";

// ABI generated by: truffle compile  (copy from build/contracts/Calculator.json → "abi" array)
const CONTRACT_ABI = [
  {
    "anonymous": false,
    "inputs": [
      { "indexed": false, "internalType": "string",  "name": "operation", "type": "string"  },
      { "indexed": false, "internalType": "int256",  "name": "a",         "type": "int256"  },
      { "indexed": false, "internalType": "int256",  "name": "b",         "type": "int256"  },
      { "indexed": false, "internalType": "int256",  "name": "result",    "type": "int256"  }
    ],
    "name": "Calculated",
    "type": "event"
  },
  {
    "inputs": [
      { "internalType": "int256", "name": "a", "type": "int256" },
      { "internalType": "int256", "name": "b", "type": "int256" }
    ],
    "name": "add",
    "outputs": [{ "internalType": "int256", "name": "", "type": "int256" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "int256", "name": "a", "type": "int256" },
      { "internalType": "int256", "name": "b", "type": "int256" }
    ],
    "name": "subtract",
    "outputs": [{ "internalType": "int256", "name": "", "type": "int256" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "int256", "name": "a", "type": "int256" },
      { "internalType": "int256", "name": "b", "type": "int256" }
    ],
    "name": "multiply",
    "outputs": [{ "internalType": "int256", "name": "", "type": "int256" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "int256", "name": "a", "type": "int256" },
      { "internalType": "int256", "name": "b", "type": "int256" }
    ],
    "name": "divide",
    "outputs": [{ "internalType": "int256", "name": "", "type": "int256" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lastResult",
    "outputs": [{ "internalType": "int256", "name": "", "type": "int256" }],
    "stateMutability": "view",
    "type": "function"
  }
];

async function connectMetaMask() {
  if (typeof window.ethereum === "undefined") {
    showStatus("MetaMask is not installed. Please install it first.", "error");
    return;
  }

  try {
    const accounts = await window.ethereum.request({ method: "eth_requestAccounts" });
    userAccount = accounts[0];

    web3 = new Web3(window.ethereum);

    document.getElementById("account").textContent = userAccount;

    if (CONTRACT_ADDRESS === "YOUR_CONTRACT_ADDRESS_HERE") {
      showStatus(
        "MetaMask connected! Now deploy the contract and paste its address into app.js (CONTRACT_ADDRESS).",
        "info"
      );
      return;
    }

    contract = new web3.eth.Contract(CONTRACT_ABI, CONTRACT_ADDRESS);
    showStatus("Wallet connected and contract loaded. Ready to calculate.", "success");

    window.ethereum.on("accountsChanged", (accs) => {
      userAccount = accs[0];
      document.getElementById("account").textContent = userAccount || "Disconnected";
    });
  } catch (err) {
    showStatus("Connection failed: " + err.message, "error");
  }
}

async function calculate(operation) {
  if (!contract) {
    showStatus("Connect MetaMask and set the contract address first.", "error");
    return;
  }

  const rawA = document.getElementById("numA").value.trim();
  const rawB = document.getElementById("numB").value.trim();

  if (rawA === "" || rawB === "") {
    showStatus("Please enter both numbers.", "error");
    return;
  }

  const a = rawA;
  const b = rawB;

  if (operation === "divide" && Number(b) === 0) {
    showStatus("Division by zero is not allowed.", "error");
    return;
  }

  const opLabels = { add: "+", subtract: "-", multiply: "*", divide: "/" };
  showStatus(`Sending transaction: ${a} ${opLabels[operation]} ${b} ...`, "info");

  const resultEl = document.getElementById("result");
  const txEl     = document.getElementById("txHash");

  resultEl.textContent = "...";
  resultEl.className   = "pending";
  txEl.style.display   = "none";

  try {
    const tx = await contract.methods[operation](a, b).send({ from: userAccount });

    const raw = await contract.methods.lastResult().call();
    const value = BigInt(raw).toString();

    resultEl.textContent = value;
    resultEl.className   = "";

    txEl.textContent     = "Tx: " + tx.transactionHash;
    txEl.style.display   = "block";

    showStatus("Calculation complete.", "success");
  } catch (err) {
    resultEl.textContent = "—";
    resultEl.className   = "pending";
    showStatus("Error: " + (err.message || err), "error");
  }
}

function showStatus(msg, type) {
  const el = document.getElementById("status");
  el.textContent  = msg;
  el.className    = "status " + type;
}
